# 类别转义
    def category_index(self, category):
        try:
            p_c_index = []
            if self.invoce_type == 'input':
                if category == '福利费':
                    p_c_index = [0, 0]
                elif category == '劳务费':
                    p_c_index = [0, 1]
                elif category == '招待费':
                    p_c_index = [1, 0]
                elif category == '办公费':
                    p_c_index = [1, 1]
                elif category == '快递费':
                    p_c_index = [1, 2]
                elif category == '通讯费':
                    p_c_index = [1, 3]
                elif category == '维修费':
                    p_c_index = [1, 4]
                elif category == '财产保险费':
                    p_c_index = [1, 5]
                elif category == '设备租赁费':
                    p_c_index = [1, 6]
                elif category == '银行费用':
                    p_c_index = [1, 7]
                elif category == '差旅费':
                    p_c_index = [2, 0]
                elif category == '交通费':
                    p_c_index = [2, 1]
                elif category == '汽油费':
                    p_c_index = [2, 2]
                elif category == '路桥费':
                    p_c_index = [2, 3]
                elif category == '汽车维修费':
                    p_c_index = [2, 4]
                elif category == '汽车保险费':
                    p_c_index = [2, 5]
                elif category == '物流费':
                    p_c_index = [2, 6]
                elif category == '房租费':
                    p_c_index = [3, 0]
                elif category == '物业费':
                    p_c_index = [3, 1]
                elif category == '水费':
                    p_c_index = [3, 2]
                elif category == '电费':
                    p_c_index = [3, 3]
                elif category == '仓储费':
                    p_c_index = [3, 4]
                elif category == '装修费':
                    p_c_index = [3, 5]
                elif category == '广告费':
                    p_c_index = [4, 0]
                elif category == '宣传费':
                    p_c_index = [4, 1]
                elif category == '研发费':
                    p_c_index = [4, 2]
                elif category == '会议费':
                    p_c_index = [4, 3]
                elif category == '服务费':
                    p_c_index = [4, 4]
                elif category == '咨询费':
                    p_c_index = [4, 5]
                elif category == '认证费':
                    p_c_index = [4, 6]
                elif category == '专利费':
                    p_c_index = [4, 7]
                elif category == '工会经费':
                    p_c_index = [4, 8]
                elif category == '其他':
                    p_c_index = [4, 9]
                elif category == '行政罚款':
                    p_c_index = [5, 0]
                elif category == '税务滞纳金':
                    p_c_index = [5, 1]
                elif category == '印花税':
                    p_c_index = [6, 0]
                elif category == '残保金':
                    p_c_index = [6, 1]
                elif category == '减免税款':
                    p_c_index = [6, 2]
                elif category == '原材料':
                    p_c_index = [7, 0]
                elif category == '商品产品':
                    p_c_index = [7, 1]
            elif self.invoce_type == 'output':
                if category == '商品销售':
                    p_c_index = [0, 0]
                elif category == '服务收入':
                    p_c_index = [1, 0]
            else:
                return 'error'
        except Exception as e:
            print('')
